title: Gallery
subtitle: Means88's memory library
favicon: 'https://means88.com/favicon.ico'
avatar: 'https://means88.com/static/media/avatar.2316da1abd928fe5f335.jpeg'
description: さあ、旅に出よう、忘れないうちに
cover: 'https://cdn.jsdelivr.net/gh/Means88/picx-images-hosting@master/example/1.webp'
author: Means88

footer_logo:
  use: self
  self:
    link: 'https://means88.com/'
    src: 'https://means88.com/static/media/avatar.2316da1abd928fe5f335.jpeg'

url: https://photo.means88.com/
root: /

busuanzi: false

photography_page:
  slogan: true
  slogan_descr: 'さあ、旅に出よう、忘れないうちに'
  travel_slogan: true
  travel_slogan_descr: 'わたし今探しに行きたい'

google_analytics:
  use: gtag
  ga_id:
  ga_api:
  gtag_id: G-8TMSDJG47Q

nav:
  地图:
    link: /location
    icon: local-two
  随机:
    link: /random
    icon: pic
  时间线:
    link: /grid-all
    icon: grid-nine

thumbnail_url: https://cdn.jsdelivr.net/gh/Means88/picx-images-hosting@thumbnail/
base_url: https://cdn.jsdelivr.net/gh/Means88/picx-images-hosting@master
backup_base_url: https://raw.githubusercontent.com/Means88/picx-images-hosting/master
backup_thumbnail_url: https://raw.githubusercontent.com/Means88/picx-images-hosting/thumbnail